-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 12:58:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Clinica14
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Clinica14
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Clinica14` DEFAULT CHARACTER SET utf8 ;
USE `Clinica14` ;

-- -----------------------------------------------------
-- Table `Clinica14`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Cpf` INT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` BIGINT(14) NULL,
  `Senha` VARCHAR(250) NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica14`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`Conta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Saldo` DECIMAL(9,2) NOT NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_conta_Usuario1_idx` (`Usuario_Id` ASC),
  CONSTRAINT `fk_conta_Usuario1`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `Clinica14`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica14`.`Plano_Contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`Plano_Contas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `Tipo` CHAR(1) NOT NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Plano_Contas_Usuario1_idx` (`Usuario_Id` ASC),
  CONSTRAINT `fk_Plano_Contas_Usuario1`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `Clinica14`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica14`.`Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`Transacao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Data` DATETIME NOT NULL,
  `Tipo` CHAR(1) NOT NULL,
  `Valor` DECIMAL(9,2) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Conta_Id` INT NOT NULL,
  `Plano_Contas_Id` INT NOT NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Transacao_Conta1_idx` (`Conta_Id` ASC),
  INDEX `fk_Transacao_Plano_Contas1_idx` (`Plano_Contas_Id` ASC),
  INDEX `fk_Transacao_Usuario1_idx` (`Usuario_Id` ASC),
  CONSTRAINT `fk_Transacao_Conta1`
    FOREIGN KEY (`Conta_Id`)
    REFERENCES `Clinica14`.`Conta` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Plano_Contas1`
    FOREIGN KEY (`Plano_Contas_Id`)
    REFERENCES `Clinica14`.`Plano_Contas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Usuario1`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `Clinica14`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica14`.`funcinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`funcinario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Cpf` INT NOT NULL,
  `RG` INT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  `Telefone` BIGINT(14) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica14`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`servico` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(150) NOT NULL,
  `Tipo` VARCHAR(100) NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `Observacao` VARCHAR(150) NULL,
  `Data_Servico` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica14`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`Pagamento` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Avista` VARCHAR(45) NULL,
  `Cartao` VARCHAR(45) NULL,
  `Prazo` VARCHAR(45) NULL,
  `Descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica14`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`cliente` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Cpf` INT NOT NULL,
  `Rg` INT NULL,
  `Data_Nascimento` DATE NOT NULL,
  `Endereco` VARCHAR(150) NOT NULL,
  `Bairro` VARCHAR(50) NULL,
  `Cidade` VARCHAR(50) NOT NULL,
  `Telefone` BINARY(14) NULL,
  `Celular` INT NULL,
  `Email` VARCHAR(150) NULL,
  `Profissao` VARCHAR(150) NULL,
  `Descricao` VARCHAR(150) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica14`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica14`.`consulta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Obsevarcoes` VARCHAR(150) NULL,
  `Hora_Consulta` TIME NULL,
  `Data_Consulta` DATE NOT NULL,
  `servico_Id` INT NOT NULL,
  `funcinario_Id` INT NOT NULL,
  `Pagamento_Id` INT NOT NULL,
  `Usuario_Id` INT NOT NULL,
  `cliente_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_consulta_servico1_idx` (`servico_Id` ASC),
  INDEX `fk_consulta_funcinario1_idx` (`funcinario_Id` ASC),
  INDEX `fk_consulta_Pagamento1_idx` (`Pagamento_Id` ASC),
  INDEX `fk_consulta_Usuario1_idx` (`Usuario_Id` ASC),
  INDEX `fk_consulta_cliente1_idx` (`cliente_Id` ASC),
  CONSTRAINT `fk_consulta_servico1`
    FOREIGN KEY (`servico_Id`)
    REFERENCES `Clinica14`.`servico` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_funcinario1`
    FOREIGN KEY (`funcinario_Id`)
    REFERENCES `Clinica14`.`funcinario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_Pagamento1`
    FOREIGN KEY (`Pagamento_Id`)
    REFERENCES `Clinica14`.`Pagamento` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_Usuario1`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `Clinica14`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_cliente1`
    FOREIGN KEY (`cliente_Id`)
    REFERENCES `Clinica14`.`cliente` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
